apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service-deployment
  namespace: intelligtest-namespace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app/component: test-service
  template:
    metadata:
      name: test-service-pod
      labels:
        app/name: test-service-pod
        app/component: test-service
    spec:
      containers:
        - name: test-service-container
          image: zaragozasebastian/test-service-intelligtest:1
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 4003
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  key: PORT
                  name: test-service-secrets
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: test-service-secrets

