apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: intelligtest-namespace
spec:
  selector:
    app/component: test-service
  ports:
    - port: 4003
      targetPort: 4003
  type: ClusterIP
