apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: intelligtest-namespace
type: Opaque
stringData:
  PORT: "3000"
  JWT_SECRET: "bO~3v@Sj+^Bvc8'"
  FRONTEND_URL: "http://localhost:5173"
  