apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: intelligtest-namespace
spec:
  selector:
    app/component: api-gateway
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
