apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service-deployment
  namespace: intelligtest-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app/component: notes-service
  template:
    metadata:
      name: notes-service-pod
      labels:
        app/name: notes-service-pod
        app/component: notes-service
    spec:
      containers:
        - name: notes-service-container
          image: zaragozasebastian/notes-service-intelligtest:8
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  key: PORT
                  name: notes-service-secrets
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: notes-service-secrets

