apiVersion: v1
kind: Secret
metadata:
  name: notes-service-secrets
  namespace: intelligtest-namespace
type: Opaque
stringData:
  DATABASE_URL: "mongodb+srv://galindozaragozasebastian:FQqaLgugTSJjguR0@intelligtest.cqdk7op.mongodb.net/notes"
  PORT: "4002"
