apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-service-deployment
  namespace: intelligtest-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app/component: section-service
  template:
    metadata:
      name: section-service-pod
      labels:
        app/name: section-service-pod
        app/component: section-service
    spec:
      containers:
        - name: section-service-container
          image: zaragozasebastian/section-service-intelligtest:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  key: PORT
                  name: section-service-secrets
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: section-service-secrets

