apiVersion: v1
kind: Secret
metadata:
  name: section-service-secrets
  namespace: intelligtest-namespace
type: Opaque
stringData:
  DATABASE_URL: "mongodb+srv://galindozaragozasebastian:FQqaLgugTSJjguR0@intelligtest.cqdk7op.mongodb.net/sections"
  PORT: "4000"